---

- name: "deploy backend play"
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
    - name: "Debug 1"
      ansible.builtin.shell:
        cmd: pwd

    - name: "Debug 2"
      ansible.builtin.shell:
        cmd: ls -l

    - name: "Copy source and node_modules"
      ansible.builtin.copy:
        src: ~/project/backend
        dest: ./

    - name: "Copy built assets"
      ansible.builtin.copy:
        src: ~/workspace/backend/dist
        dest: ./backend

    - name: "Debug 3"
      ansible.builtin.shell:
        cmd: ls -l

    - name: "NPM install"
      ansible.builtin.shell:
        chdir: ~/backend
        cmd: npm install

    - name: "Start the service"
      ansible.builtin.shell: |
        cd ~/backend
        screen -d -m npm run start 2>&1 </dev/null >output.log

  environment:
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_MIGRATIONS_DIR: ./src/migrations
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"

  # roles:
  #   - deploy
